[project]
name = "robot-code"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python= ">=3.12"

dependencies = [
    "pygls>=2.0",
    "python-dotenv>=1.1.0",
    "requests>=2.32.4",
    "semver>=3.0.4",
]

[project.scripts]
fs = "fs_cli.cli:run"
fs-lsp = "fs_lsp.server:main"

[dependency-groups]
dev = ["pytest>=8.0.0"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["*test*.py"]

[tool.hatch.build.targets.wheel]
packages = ["onshape_api", "fs_cli", "fs_lsp", "featurescript", "robot_code"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
