FeatureScript 2960;
import(path : "onshape/std/common.fs", version : "2960.0");

/* Generated from robotBeltTables.py by `fs gen` -- DO NOT EDIT */

export enum BeltType
{
    _2_MM_GT2,
    _3_MM_GT2,
    _3_MM_HTD,
    _5_MM_HTD,
    RT25,
}

export const beltTable = {
        "name" : "beltType",
        "displayName" : "Belt type",
        "default" : "5mm HTD",
        "entries" : {
            "2mm GT2" : {
                "name" : "supplier",
                "displayName" : "Belt supplier",
                "entries" : {
                    "goBILDA" : {
                        "name" : "teeth",
                        "displayName" : "Teeth",
                        "entries" : {
                            "44T" : { "beltTeeth" : 44, "beltType" : BeltType._2_MM_GT2, "beltWidth" : 6 * millimeter },
                            "68T" : { "beltTeeth" : 68, "beltType" : BeltType._2_MM_GT2, "beltWidth" : 6 * millimeter },
                            "92T" : { "beltTeeth" : 92, "beltType" : BeltType._2_MM_GT2, "beltWidth" : 6 * millimeter },
                            "108T" : { "beltTeeth" : 108, "beltType" : BeltType._2_MM_GT2, "beltWidth" : 6 * millimeter },
                            "116T" : { "beltTeeth" : 116, "beltType" : BeltType._2_MM_GT2, "beltWidth" : 6 * millimeter },
                            "132T" : { "beltTeeth" : 132, "beltType" : BeltType._2_MM_GT2, "beltWidth" : 6 * millimeter },
                            "140T" : { "beltTeeth" : 140, "beltType" : BeltType._2_MM_GT2, "beltWidth" : 6 * millimeter },
                            "156T" : { "beltTeeth" : 156, "beltType" : BeltType._2_MM_GT2, "beltWidth" : 6 * millimeter },
                            "164T" : { "beltTeeth" : 164, "beltType" : BeltType._2_MM_GT2, "beltWidth" : 6 * millimeter },
                            "180T" : { "beltTeeth" : 180, "beltType" : BeltType._2_MM_GT2, "beltWidth" : 6 * millimeter },
                            "188T" : { "beltTeeth" : 188, "beltType" : BeltType._2_MM_GT2, "beltWidth" : 6 * millimeter },
                            "204T" : { "beltTeeth" : 204, "beltType" : BeltType._2_MM_GT2, "beltWidth" : 6 * millimeter },
                            "209T" : { "beltTeeth" : 209, "beltType" : BeltType._2_MM_GT2, "beltWidth" : 6 * millimeter },
                            "212T" : { "beltTeeth" : 212, "beltType" : BeltType._2_MM_GT2, "beltWidth" : 6 * millimeter },
                            "228T" : { "beltTeeth" : 228, "beltType" : BeltType._2_MM_GT2, "beltWidth" : 6 * millimeter },
                            "233T" : { "beltTeeth" : 233, "beltType" : BeltType._2_MM_GT2, "beltWidth" : 6 * millimeter },
                            "236T" : { "beltTeeth" : 236, "beltType" : BeltType._2_MM_GT2, "beltWidth" : 6 * millimeter },
                            "252T" : { "beltTeeth" : 252, "beltType" : BeltType._2_MM_GT2, "beltWidth" : 6 * millimeter },
                            "257T" : { "beltTeeth" : 257, "beltType" : BeltType._2_MM_GT2, "beltWidth" : 6 * millimeter },
                            "276T" : { "beltTeeth" : 276, "beltType" : BeltType._2_MM_GT2, "beltWidth" : 6 * millimeter },
                            "300T" : { "beltTeeth" : 300, "beltType" : BeltType._2_MM_GT2, "beltWidth" : 6 * millimeter },
                            "324T" : { "beltTeeth" : 324, "beltType" : BeltType._2_MM_GT2, "beltWidth" : 6 * millimeter },
                        },
                    },
                    "Custom" : { "beltType" : BeltType._2_MM_GT2, "beltWidth" : 6 * millimeter },
                },
            },
            "3mm GT2" : {
                "name" : "supplier",
                "displayName" : "Belt supplier",
                "entries" : {
                    "WCP" : {
                        "name" : "teeth",
                        "displayName" : "Teeth",
                        "entries" : {
                            "45T" : { "beltTeeth" : 45, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                            "50T" : { "beltTeeth" : 50, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                            "55T" : { "beltTeeth" : 55, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                            "60T" : { "beltTeeth" : 60, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                            "65T" : { "beltTeeth" : 65, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                            "70T" : { "beltTeeth" : 70, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                            "75T" : { "beltTeeth" : 75, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                            "80T" : { "beltTeeth" : 80, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                            "85T" : { "beltTeeth" : 85, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                            "90T" : { "beltTeeth" : 90, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                            "95T" : { "beltTeeth" : 95, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                            "100T" : { "beltTeeth" : 100, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                            "105T" : { "beltTeeth" : 105, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                            "110T" : { "beltTeeth" : 110, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                            "115T" : { "beltTeeth" : 115, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                            "120T" : { "beltTeeth" : 120, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                            "125T" : { "beltTeeth" : 125, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                            "130T" : { "beltTeeth" : 130, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                            "140T" : { "beltTeeth" : 140, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                            "150T" : { "beltTeeth" : 150, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                            "160T" : { "beltTeeth" : 160, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                            "170T" : { "beltTeeth" : 170, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                            "180T" : { "beltTeeth" : 180, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                            "190T" : { "beltTeeth" : 190, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                            "200T" : { "beltTeeth" : 200, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                        },
                    },
                    "REV" : {
                        "name" : "teeth",
                        "displayName" : "Teeth",
                        "entries" : {
                            "55T" : { "beltTeeth" : 55, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                            "85T" : { "beltTeeth" : 85, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                            "105T" : { "beltTeeth" : 105, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                            "120T" : { "beltTeeth" : 120, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                            "145T" : { "beltTeeth" : 145, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                            "184T" : { "beltTeeth" : 184, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                            "210T" : { "beltTeeth" : 210, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                            "270T" : { "beltTeeth" : 270, "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                        },
                    },
                    "Custom" : { "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
                },
            },
            "3mm HTD" : {
                "name" : "supplier",
                "displayName" : "Belt supplier",
                "entries" : {
                    "goBILDA" : {
                        "name" : "teeth",
                        "displayName" : "Teeth",
                        "entries" : {
                            "68T" : { "beltTeeth" : 68, "beltType" : BeltType._3_MM_HTD, "beltWidth" : 15 * millimeter },
                            "84T" : { "beltTeeth" : 84, "beltType" : BeltType._3_MM_HTD, "beltWidth" : 15 * millimeter },
                            "100T" : { "beltTeeth" : 100, "beltType" : BeltType._3_MM_HTD, "beltWidth" : 15 * millimeter },
                            "116T" : { "beltTeeth" : 116, "beltType" : BeltType._3_MM_HTD, "beltWidth" : 15 * millimeter },
                            "132T" : { "beltTeeth" : 132, "beltType" : BeltType._3_MM_HTD, "beltWidth" : 15 * millimeter },
                            "148T" : { "beltTeeth" : 148, "beltType" : BeltType._3_MM_HTD, "beltWidth" : 15 * millimeter },
                            "164T" : { "beltTeeth" : 164, "beltType" : BeltType._3_MM_HTD, "beltWidth" : 15 * millimeter },
                            "180T" : { "beltTeeth" : 180, "beltType" : BeltType._3_MM_HTD, "beltWidth" : 15 * millimeter },
                            "212T" : { "beltTeeth" : 212, "beltType" : BeltType._3_MM_HTD, "beltWidth" : 15 * millimeter },
                            "228T" : { "beltTeeth" : 228, "beltType" : BeltType._3_MM_HTD, "beltWidth" : 15 * millimeter },
                            "244T" : { "beltTeeth" : 244, "beltType" : BeltType._3_MM_HTD, "beltWidth" : 15 * millimeter },
                            "260T" : { "beltTeeth" : 260, "beltType" : BeltType._3_MM_HTD, "beltWidth" : 15 * millimeter },
                            "276T" : { "beltTeeth" : 276, "beltType" : BeltType._3_MM_HTD, "beltWidth" : 15 * millimeter },
                            "292T" : { "beltTeeth" : 292, "beltType" : BeltType._3_MM_HTD, "beltWidth" : 15 * millimeter },
                        },
                    },
                    "Custom" : { "beltType" : BeltType._3_MM_HTD, "beltWidth" : 15 * millimeter },
                },
            },
            "5mm HTD" : {
                "name" : "width",
                "displayName" : "Belt width",
                "entries" : {
                    "9 mm" : {
                        "name" : "supplier",
                        "displayName" : "Belt supplier",
                        "entries" : {
                            "WCP" : {
                                "name" : "teeth",
                                "displayName" : "Teeth",
                                "entries" : {
                                    "30T" : { "beltTeeth" : 30, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "35T" : { "beltTeeth" : 35, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "40T" : { "beltTeeth" : 40, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "43T" : { "beltTeeth" : 43, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "45T" : { "beltTeeth" : 45, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "50T" : { "beltTeeth" : 50, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "53T" : { "beltTeeth" : 53, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "55T" : { "beltTeeth" : 55, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "60T" : { "beltTeeth" : 60, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "64T" : { "beltTeeth" : 64, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "65T" : { "beltTeeth" : 65, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "70T" : { "beltTeeth" : 70, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "75T" : { "beltTeeth" : 75, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "80T" : { "beltTeeth" : 80, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "85T" : { "beltTeeth" : 85, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "90T" : { "beltTeeth" : 90, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "95T" : { "beltTeeth" : 95, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "100T" : { "beltTeeth" : 100, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "104T" : { "beltTeeth" : 104, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "105T" : { "beltTeeth" : 105, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "110T" : { "beltTeeth" : 110, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "115T" : { "beltTeeth" : 115, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "120T" : { "beltTeeth" : 120, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "125T" : { "beltTeeth" : 125, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "130T" : { "beltTeeth" : 130, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "135T" : { "beltTeeth" : 135, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "140T" : { "beltTeeth" : 140, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "145T" : { "beltTeeth" : 145, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "150T" : { "beltTeeth" : 150, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "155T" : { "beltTeeth" : 155, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "160T" : { "beltTeeth" : 160, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "165T" : { "beltTeeth" : 165, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "170T" : { "beltTeeth" : 170, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "175T" : { "beltTeeth" : 175, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "180T" : { "beltTeeth" : 180, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "185T" : { "beltTeeth" : 185, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "190T" : { "beltTeeth" : 190, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "195T" : { "beltTeeth" : 195, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "200T" : { "beltTeeth" : 200, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "210T" : { "beltTeeth" : 210, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "220T" : { "beltTeeth" : 220, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "225T" : { "beltTeeth" : 225, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "230T" : { "beltTeeth" : 230, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "240T" : { "beltTeeth" : 240, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "250T" : { "beltTeeth" : 250, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "260T" : { "beltTeeth" : 260, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "270T" : { "beltTeeth" : 270, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "280T" : { "beltTeeth" : 280, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "290T" : { "beltTeeth" : 290, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "300T" : { "beltTeeth" : 300, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                },
                            },
                            "AndyMark" : {
                                "name" : "teeth",
                                "displayName" : "Teeth",
                                "entries" : {
                                    "30T" : { "beltTeeth" : 30, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "35T" : { "beltTeeth" : 35, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "40T" : { "beltTeeth" : 40, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "45T" : { "beltTeeth" : 45, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "48T" : { "beltTeeth" : 48, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "50T" : { "beltTeeth" : 50, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "55T" : { "beltTeeth" : 55, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "60T" : { "beltTeeth" : 60, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "64T" : { "beltTeeth" : 64, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "65T" : { "beltTeeth" : 65, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "70T" : { "beltTeeth" : 70, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "75T" : { "beltTeeth" : 75, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "80T" : { "beltTeeth" : 80, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "85T" : { "beltTeeth" : 85, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "90T" : { "beltTeeth" : 90, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "91T" : { "beltTeeth" : 91, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "93T" : { "beltTeeth" : 93, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "95T" : { "beltTeeth" : 95, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "100T" : { "beltTeeth" : 100, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "105T" : { "beltTeeth" : 105, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "106T" : { "beltTeeth" : 106, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "110T" : { "beltTeeth" : 110, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "115T" : { "beltTeeth" : 115, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "120T" : { "beltTeeth" : 120, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "121T" : { "beltTeeth" : 121, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "125T" : { "beltTeeth" : 125, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "130T" : { "beltTeeth" : 130, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "135T" : { "beltTeeth" : 135, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "136T" : { "beltTeeth" : 136, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "140T" : { "beltTeeth" : 140, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "145T" : { "beltTeeth" : 145, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "150T" : { "beltTeeth" : 150, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "152T" : { "beltTeeth" : 152, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "160T" : { "beltTeeth" : 160, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "167T" : { "beltTeeth" : 167, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "170T" : { "beltTeeth" : 170, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "180T" : { "beltTeeth" : 180, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "190T" : { "beltTeeth" : 190, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "200T" : { "beltTeeth" : 200, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "225T" : { "beltTeeth" : 225, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "250T" : { "beltTeeth" : 250, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                },
                            },
                            "The Thrifty Bot" : {
                                "name" : "teeth",
                                "displayName" : "Teeth",
                                "entries" : {
                                    "35T" : { "beltTeeth" : 35, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "40T" : { "beltTeeth" : 40, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "45T" : { "beltTeeth" : 45, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "50T" : { "beltTeeth" : 50, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "55T" : { "beltTeeth" : 55, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "60T" : { "beltTeeth" : 60, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "65T" : { "beltTeeth" : 65, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "70T" : { "beltTeeth" : 70, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "75T" : { "beltTeeth" : 75, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "80T" : { "beltTeeth" : 80, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "85T" : { "beltTeeth" : 85, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "90T" : { "beltTeeth" : 90, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "95T" : { "beltTeeth" : 95, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "100T" : { "beltTeeth" : 100, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "105T" : { "beltTeeth" : 105, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "110T" : { "beltTeeth" : 110, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "115T" : { "beltTeeth" : 115, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "120T" : { "beltTeeth" : 120, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "125T" : { "beltTeeth" : 125, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "130T" : { "beltTeeth" : 130, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "135T" : { "beltTeeth" : 135, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "140T" : { "beltTeeth" : 140, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "145T" : { "beltTeeth" : 145, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "150T" : { "beltTeeth" : 150, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "155T" : { "beltTeeth" : 155, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "160T" : { "beltTeeth" : 160, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "165T" : { "beltTeeth" : 165, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "170T" : { "beltTeeth" : 170, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "175T" : { "beltTeeth" : 175, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "180T" : { "beltTeeth" : 180, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "185T" : { "beltTeeth" : 185, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "190T" : { "beltTeeth" : 190, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "195T" : { "beltTeeth" : 195, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "200T" : { "beltTeeth" : 200, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "210T" : { "beltTeeth" : 210, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "220T" : { "beltTeeth" : 220, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "230T" : { "beltTeeth" : 230, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "240T" : { "beltTeeth" : 240, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "250T" : { "beltTeeth" : 250, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "260T" : { "beltTeeth" : 260, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "270T" : { "beltTeeth" : 270, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "280T" : { "beltTeeth" : 280, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "290T" : { "beltTeeth" : 290, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "300T" : { "beltTeeth" : 300, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                },
                            },
                            "goBILDA" : {
                                "name" : "teeth",
                                "displayName" : "Teeth",
                                "entries" : {
                                    "43T" : { "beltTeeth" : 43, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "45T" : { "beltTeeth" : 45, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "49T" : { "beltTeeth" : 49, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "53T" : { "beltTeeth" : 53, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "55T" : { "beltTeeth" : 55, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "59T" : { "beltTeeth" : 59, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "63T" : { "beltTeeth" : 63, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "64T" : { "beltTeeth" : 64, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "68T" : { "beltTeeth" : 68, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "72T" : { "beltTeeth" : 72, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "74T" : { "beltTeeth" : 74, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "76T" : { "beltTeeth" : 76, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "78T" : { "beltTeeth" : 78, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "82T" : { "beltTeeth" : 82, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "84T" : { "beltTeeth" : 84, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "85T" : { "beltTeeth" : 85, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "89T" : { "beltTeeth" : 89, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "92T" : { "beltTeeth" : 92, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "94T" : { "beltTeeth" : 94, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "97T" : { "beltTeeth" : 97, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "101T" : { "beltTeeth" : 101, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "104T" : { "beltTeeth" : 104, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "107T" : { "beltTeeth" : 107, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                    "112T" : { "beltTeeth" : 112, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                                },
                            },
                            "Custom" : { "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                        },
                    },
                    "15 mm" : {
                        "name" : "supplier",
                        "displayName" : "Belt supplier",
                        "entries" : {
                            "WCP" : {
                                "name" : "teeth",
                                "displayName" : "Teeth",
                                "entries" : {
                                    "30T" : { "beltTeeth" : 30, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "35T" : { "beltTeeth" : 35, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "40T" : { "beltTeeth" : 40, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "45T" : { "beltTeeth" : 45, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "50T" : { "beltTeeth" : 50, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "55T" : { "beltTeeth" : 55, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "60T" : { "beltTeeth" : 60, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "64T" : { "beltTeeth" : 64, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "65T" : { "beltTeeth" : 65, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "70T" : { "beltTeeth" : 70, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "75T" : { "beltTeeth" : 75, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "80T" : { "beltTeeth" : 80, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "85T" : { "beltTeeth" : 85, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "90T" : { "beltTeeth" : 90, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "95T" : { "beltTeeth" : 95, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "100T" : { "beltTeeth" : 100, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "104T" : { "beltTeeth" : 104, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "105T" : { "beltTeeth" : 105, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "110T" : { "beltTeeth" : 110, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "115T" : { "beltTeeth" : 115, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "120T" : { "beltTeeth" : 120, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "125T" : { "beltTeeth" : 125, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "130T" : { "beltTeeth" : 130, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "135T" : { "beltTeeth" : 135, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "140T" : { "beltTeeth" : 140, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "145T" : { "beltTeeth" : 145, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "150T" : { "beltTeeth" : 150, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "155T" : { "beltTeeth" : 155, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "160T" : { "beltTeeth" : 160, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "165T" : { "beltTeeth" : 165, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "170T" : { "beltTeeth" : 170, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "175T" : { "beltTeeth" : 175, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "180T" : { "beltTeeth" : 180, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "185T" : { "beltTeeth" : 185, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "190T" : { "beltTeeth" : 190, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "195T" : { "beltTeeth" : 195, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "200T" : { "beltTeeth" : 200, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "210T" : { "beltTeeth" : 210, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "220T" : { "beltTeeth" : 220, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "225T" : { "beltTeeth" : 225, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "230T" : { "beltTeeth" : 230, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "240T" : { "beltTeeth" : 240, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "250T" : { "beltTeeth" : 250, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "260T" : { "beltTeeth" : 260, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "270T" : { "beltTeeth" : 270, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "280T" : { "beltTeeth" : 280, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "290T" : { "beltTeeth" : 290, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "300T" : { "beltTeeth" : 300, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                },
                            },
                            "AndyMark" : {
                                "name" : "teeth",
                                "displayName" : "Teeth",
                                "entries" : {
                                    "30T" : { "beltTeeth" : 30, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "35T" : { "beltTeeth" : 35, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "40T" : { "beltTeeth" : 40, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "45T" : { "beltTeeth" : 45, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "50T" : { "beltTeeth" : 50, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "55T" : { "beltTeeth" : 55, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "60T" : { "beltTeeth" : 60, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "64T" : { "beltTeeth" : 64, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "65T" : { "beltTeeth" : 65, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "70T" : { "beltTeeth" : 70, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "75T" : { "beltTeeth" : 75, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "78T" : { "beltTeeth" : 78, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "80T" : { "beltTeeth" : 80, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "85T" : { "beltTeeth" : 85, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "90T" : { "beltTeeth" : 90, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "95T" : { "beltTeeth" : 95, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "100T" : { "beltTeeth" : 100, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "104T" : { "beltTeeth" : 104, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "105T" : { "beltTeeth" : 105, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "107T" : { "beltTeeth" : 107, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "110T" : { "beltTeeth" : 110, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "115T" : { "beltTeeth" : 115, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "117T" : { "beltTeeth" : 117, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "120T" : { "beltTeeth" : 120, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "125T" : { "beltTeeth" : 125, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "130T" : { "beltTeeth" : 130, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "131T" : { "beltTeeth" : 131, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "135T" : { "beltTeeth" : 135, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "140T" : { "beltTeeth" : 140, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "145T" : { "beltTeeth" : 145, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "150T" : { "beltTeeth" : 150, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "151T" : { "beltTeeth" : 151, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "160T" : { "beltTeeth" : 160, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "170T" : { "beltTeeth" : 170, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "180T" : { "beltTeeth" : 180, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "190T" : { "beltTeeth" : 190, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "200T" : { "beltTeeth" : 200, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "210T" : { "beltTeeth" : 210, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "220T" : { "beltTeeth" : 220, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "225T" : { "beltTeeth" : 225, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "230T" : { "beltTeeth" : 230, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "240T" : { "beltTeeth" : 240, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "250T" : { "beltTeeth" : 250, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                },
                            },
                            "The Thrifty Bot" : {
                                "name" : "teeth",
                                "displayName" : "Teeth",
                                "entries" : {
                                    "35T" : { "beltTeeth" : 35, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "40T" : { "beltTeeth" : 40, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "45T" : { "beltTeeth" : 45, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "50T" : { "beltTeeth" : 50, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "55T" : { "beltTeeth" : 55, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "60T" : { "beltTeeth" : 60, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "64T" : { "beltTeeth" : 64, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "65T" : { "beltTeeth" : 65, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "70T" : { "beltTeeth" : 70, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "75T" : { "beltTeeth" : 75, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "80T" : { "beltTeeth" : 80, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "85T" : { "beltTeeth" : 85, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "90T" : { "beltTeeth" : 90, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "95T" : { "beltTeeth" : 95, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "100T" : { "beltTeeth" : 100, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "105T" : { "beltTeeth" : 105, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "110T" : { "beltTeeth" : 110, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "115T" : { "beltTeeth" : 115, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "120T" : { "beltTeeth" : 120, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "125T" : { "beltTeeth" : 125, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "130T" : { "beltTeeth" : 130, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "135T" : { "beltTeeth" : 135, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "140T" : { "beltTeeth" : 140, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "145T" : { "beltTeeth" : 145, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "150T" : { "beltTeeth" : 150, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "155T" : { "beltTeeth" : 155, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "160T" : { "beltTeeth" : 160, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "165T" : { "beltTeeth" : 165, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "170T" : { "beltTeeth" : 170, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "175T" : { "beltTeeth" : 175, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "180T" : { "beltTeeth" : 180, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "185T" : { "beltTeeth" : 185, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "190T" : { "beltTeeth" : 190, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "195T" : { "beltTeeth" : 195, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "200T" : { "beltTeeth" : 200, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "210T" : { "beltTeeth" : 210, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "220T" : { "beltTeeth" : 220, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "230T" : { "beltTeeth" : 230, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "240T" : { "beltTeeth" : 240, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "250T" : { "beltTeeth" : 250, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "260T" : { "beltTeeth" : 260, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "270T" : { "beltTeeth" : 270, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "280T" : { "beltTeeth" : 280, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "290T" : { "beltTeeth" : 290, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                    "300T" : { "beltTeeth" : 300, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                                },
                            },
                            "Custom" : { "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                        },
                    },
                    "18 mm" : {
                        "name" : "supplier",
                        "displayName" : "Belt supplier",
                        "entries" : {
                            "Custom" : { "beltType" : BeltType._5_MM_HTD, "beltWidth" : 18 * millimeter },
                        },
                    },
                },
            },
            "RT25" : {
                "name" : "supplier",
                "displayName" : "Belt supplier",
                "entries" : {
                    "REV" : {
                        "name" : "teeth",
                        "displayName" : "Teeth",
                        "entries" : {
                            "32T" : { "beltTeeth" : 32, "beltType" : BeltType.RT25, "beltWidth" : 0.5 * inch },
                            "36T" : { "beltTeeth" : 36, "beltType" : BeltType.RT25, "beltWidth" : 0.5 * inch },
                            "40T" : { "beltTeeth" : 40, "beltType" : BeltType.RT25, "beltWidth" : 0.5 * inch },
                            "48T" : { "beltTeeth" : 48, "beltType" : BeltType.RT25, "beltWidth" : 0.5 * inch },
                            "56T" : { "beltTeeth" : 56, "beltType" : BeltType.RT25, "beltWidth" : 0.5 * inch },
                            "64T" : { "beltTeeth" : 64, "beltType" : BeltType.RT25, "beltWidth" : 0.5 * inch },
                            "72T" : { "beltTeeth" : 72, "beltType" : BeltType.RT25, "beltWidth" : 0.5 * inch },
                            "80T" : { "beltTeeth" : 80, "beltType" : BeltType.RT25, "beltWidth" : 0.5 * inch },
                            "88T" : { "beltTeeth" : 88, "beltType" : BeltType.RT25, "beltWidth" : 0.5 * inch },
                            "96T" : { "beltTeeth" : 96, "beltType" : BeltType.RT25, "beltWidth" : 0.5 * inch },
                            "104T" : { "beltTeeth" : 104, "beltType" : BeltType.RT25, "beltWidth" : 0.5 * inch },
                            "112T" : { "beltTeeth" : 112, "beltType" : BeltType.RT25, "beltWidth" : 0.5 * inch },
                            "120T" : { "beltTeeth" : 120, "beltType" : BeltType.RT25, "beltWidth" : 0.5 * inch },
                            "128T" : { "beltTeeth" : 128, "beltType" : BeltType.RT25, "beltWidth" : 0.5 * inch },
                            "136T" : { "beltTeeth" : 136, "beltType" : BeltType.RT25, "beltWidth" : 0.5 * inch },
                            "144T" : { "beltTeeth" : 144, "beltType" : BeltType.RT25, "beltWidth" : 0.5 * inch },
                            "152T" : { "beltTeeth" : 152, "beltType" : BeltType.RT25, "beltWidth" : 0.5 * inch },
                            "160T" : { "beltTeeth" : 160, "beltType" : BeltType.RT25, "beltWidth" : 0.5 * inch },
                            "168T" : { "beltTeeth" : 168, "beltType" : BeltType.RT25, "beltWidth" : 0.5 * inch },
                            "176T" : { "beltTeeth" : 176, "beltType" : BeltType.RT25, "beltWidth" : 0.5 * inch },
                            "184T" : { "beltTeeth" : 184, "beltType" : BeltType.RT25, "beltWidth" : 0.5 * inch },
                            "192T" : { "beltTeeth" : 192, "beltType" : BeltType.RT25, "beltWidth" : 0.5 * inch },
                            "200T" : { "beltTeeth" : 200, "beltType" : BeltType.RT25, "beltWidth" : 0.5 * inch },
                            "208T" : { "beltTeeth" : 208, "beltType" : BeltType.RT25, "beltWidth" : 0.5 * inch },
                            "216T" : { "beltTeeth" : 216, "beltType" : BeltType.RT25, "beltWidth" : 0.5 * inch },
                        },
                    },
                    "Custom" : { "beltType" : BeltType.RT25, "beltWidth" : 0.5 * inch },
                },
            },
        },
    };

export const doubleBeltTable = {
        "name" : "beltType",
        "displayName" : "Belt type",
        "entries" : {
            "5mm HTD" : {
                "name" : "width",
                "displayName" : "Belt width",
                "entries" : {
                    "9 mm" : {
                        "name" : "supplier",
                        "displayName" : "Belt supplier",
                        "entries" : {
                            "WCP" : {
                                "name" : "teeth",
                                "displayName" : "Teeth",
                                "entries" : {
                                    "100T" : { "beltTeeth" : 100, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter, "pitch" : 5 * millimeter },
                                    "125T" : { "beltTeeth" : 125, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter, "pitch" : 5 * millimeter },
                                    "150T" : { "beltTeeth" : 150, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter, "pitch" : 5 * millimeter },
                                    "175T" : { "beltTeeth" : 175, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter, "pitch" : 5 * millimeter },
                                    "200T" : { "beltTeeth" : 200, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter, "pitch" : 5 * millimeter },
                                    "250T" : { "beltTeeth" : 250, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter, "pitch" : 5 * millimeter },
                                    "300T" : { "beltTeeth" : 300, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter, "pitch" : 5 * millimeter },
                                },
                            },
                            "The Thrifty Bot" : {
                                "name" : "teeth",
                                "displayName" : "Teeth",
                                "entries" : {
                                    "100T" : { "beltTeeth" : 100, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter, "pitch" : 5 * millimeter },
                                    "125T" : { "beltTeeth" : 125, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter, "pitch" : 5 * millimeter },
                                    "150T" : { "beltTeeth" : 150, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter, "pitch" : 5 * millimeter },
                                    "175T" : { "beltTeeth" : 175, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter, "pitch" : 5 * millimeter },
                                    "200T" : { "beltTeeth" : 200, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter, "pitch" : 5 * millimeter },
                                    "250T" : { "beltTeeth" : 250, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter, "pitch" : 5 * millimeter },
                                    "300T" : { "beltTeeth" : 300, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter, "pitch" : 5 * millimeter },
                                },
                            },
                            "Custom" : { "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter, "pitch" : 5 * millimeter },
                        },
                    },
                    "15 mm" : {
                        "name" : "supplier",
                        "displayName" : "Belt supplier",
                        "entries" : {
                            "WCP" : {
                                "name" : "teeth",
                                "displayName" : "Teeth",
                                "entries" : {
                                    "100T" : { "beltTeeth" : 100, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter, "pitch" : 5 * millimeter },
                                    "125T" : { "beltTeeth" : 125, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter, "pitch" : 5 * millimeter },
                                    "150T" : { "beltTeeth" : 150, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter, "pitch" : 5 * millimeter },
                                    "175T" : { "beltTeeth" : 175, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter, "pitch" : 5 * millimeter },
                                    "200T" : { "beltTeeth" : 200, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter, "pitch" : 5 * millimeter },
                                    "250T" : { "beltTeeth" : 250, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter, "pitch" : 5 * millimeter },
                                    "300T" : { "beltTeeth" : 300, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter, "pitch" : 5 * millimeter },
                                },
                            },
                            "The Thrifty Bot" : {
                                "name" : "teeth",
                                "displayName" : "Teeth",
                                "entries" : {
                                    "100T" : { "beltTeeth" : 100, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter, "pitch" : 5 * millimeter },
                                    "125T" : { "beltTeeth" : 125, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter, "pitch" : 5 * millimeter },
                                    "150T" : { "beltTeeth" : 150, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter, "pitch" : 5 * millimeter },
                                    "175T" : { "beltTeeth" : 175, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter, "pitch" : 5 * millimeter },
                                    "200T" : { "beltTeeth" : 200, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter, "pitch" : 5 * millimeter },
                                    "250T" : { "beltTeeth" : 250, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter, "pitch" : 5 * millimeter },
                                    "300T" : { "beltTeeth" : 300, "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter, "pitch" : 5 * millimeter },
                                },
                            },
                            "Custom" : { "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter, "pitch" : 5 * millimeter },
                        },
                    },
                },
            },
        },
    };

export const beltTypeTable = {
        "name" : "beltType",
        "displayName" : "Belt type",
        "default" : "5mm HTD",
        "entries" : {
            "2mm GT2" : { "beltType" : BeltType._2_MM_GT2, "beltWidth" : 6 * millimeter },
            "3mm GT2" : { "beltType" : BeltType._3_MM_GT2, "beltWidth" : 9 * millimeter },
            "3mm HTD" : { "beltType" : BeltType._3_MM_HTD, "beltWidth" : 15 * millimeter },
            "5mm HTD" : {
                "name" : "width",
                "displayName" : "Belt width",
                "entries" : {
                    "9 mm" : { "beltType" : BeltType._5_MM_HTD, "beltWidth" : 9 * millimeter },
                    "15 mm" : { "beltType" : BeltType._5_MM_HTD, "beltWidth" : 15 * millimeter },
                    "18 mm" : { "beltType" : BeltType._5_MM_HTD, "beltWidth" : 18 * millimeter },
                },
            },
            "RT25" : { "beltType" : BeltType.RT25, "beltWidth" : 0.5 * inch },
        },
    };
